# Build Stage
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Run Stage
FROM eclipse-temurin:17
WORKDIR /app

# Install Docker CLI so the Java backend can execute Docker commands for CodeArena
COPY --from=docker:24.0 /usr/local/bin/docker /usr/local/bin/docker

COPY --from=build /app/target/codearena-backend-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
