-- Milestone 2 Features Schema Enhancements

-- 1. Problems Table Modification: Add editorial_md
ALTER TABLE problems ADD COLUMN editorial_md TEXT;

-- 2. Problem Starter Codes Table
CREATE TABLE problem_starter_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    language VARCHAR(50) NOT NULL,
    code_template TEXT NOT NULL,
    CONSTRAINT fk_starter_codes_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE,
    CONSTRAINT uq_problem_language UNIQUE (problem_id, language)
);

-- 3. Problem Hints Table
CREATE TABLE problem_hints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT NOT NULL,
    hint_number INTEGER NOT NULL,
    hint_text TEXT NOT NULL,
    CONSTRAINT fk_hints_problem FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE,
    CONSTRAINT uq_problem_hint_number UNIQUE (problem_id, hint_number)
);

-- 4. Test Cases Table Modification: Add time_limit_override_ms
ALTER TABLE test_cases ADD COLUMN time_limit_override_ms BIGINT;

-- 5. Language Leaderboards Table
CREATE TABLE language_leaderboards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    language VARCHAR(50) NOT NULL,
    problems_solved INTEGER NOT NULL DEFAULT 0,
    accuracy DOUBLE PRECISION DEFAULT 0.0,
    rank INTEGER,
    CONSTRAINT fk_language_leaderboard_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_language UNIQUE (user_id, language)
);

-- 6. Weekly Leaderboards Table
CREATE TABLE weekly_leaderboards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    week_start_date DATE NOT NULL,
    problems_solved INTEGER NOT NULL DEFAULT 0,
    score DOUBLE PRECISION DEFAULT 0.0,
    rank INTEGER,
    CONSTRAINT fk_weekly_leaderboard_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_week UNIQUE (user_id, week_start_date)
);
